# Welcome to Jekyll!
#

# Site settings
title: StraightUp.wtf
description: |
  Just puttin it out there
owner: StraightUp.wtf # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: hello@straightup.wtf
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://straightup.wtf" # the base hostname & protocol for your site
permalink: /blog/:slug:output_ext
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"


# Build settings
markdown: kramdown
#sass:
#  style: compressed
incremental: false
